### ISSUE TITLE
Get someone to run a usability test.

### ISSUE THREAD

**Issue by seth-way** [CarissaHluchan/whats-cookin#28]

**Comment by seth-way** [comment]
1. Ask someone from another project group to be the tester (participant)
2. Schedule a time to do the usability test with the participant
3. Create a script for the usability test
    - Decide what you are trying to learn from the usability test (can a user do [blank]? can a user find [blank] and know how to use it? do they notice [blank] information on the page?).
    - Write step-by-step instructions for the participant doing the usability test to follow as you observe them.
    - After the observation is done, prepare a few questions to ask the participant about how they felt while they were trying the feature.
    - The usability test should not last for more than 30 minutes
4. Perform the test and take notes
5. Incorporate any valuable feedback into your application

**Comment by CarissaHluchan** [comment]
Had Chris Hluchan follow the user prompts. 
Notes are in the Document: [UI testing](https://docs.google.com/document/d/1-T_6ua190-IrRTZwsU8lxX8DCpVu2plhhpd5fEdRRE4/edit)
